=== sofiadutta/Data-Science-IPython-Notebooks/fall2019/schedule.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="schedule">
        <xs:annotation>
            <xs:documentation>Schedule is the root element.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="course" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="programIdentifier">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="4" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="number">
                                <xs:simpleType>
                                    <xs:restriction base="xs:nonNegativeInteger" />
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="title">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="credit">
                                <xs:simpleType>
																	<xs:restriction base="xs:nonNegativeInteger" />
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="prerequisite">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="0" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="description">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="section" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="sectionNumber">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="2" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="instructor">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="2" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="classNumber">
                                            <xs:simpleType>
																							<xs:restriction base="xs:nonNegativeInteger" />
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="room">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="2" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="days">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="2" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="startTime">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="2" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="endTime">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="2" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="status">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="2" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
						<xs:attribute name="year" type="xs:gYear" use="required" />
						<xs:attribute name="semester" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sofiadutta/Data-Science-IPython-Notebooks/fall2019/fall2019.xml
<?xml version="1.0" encoding="UTF-16"?>
<?xml-stylesheet type="text/xsl" href="https://sofiadutta.github.io/fall2019/schedule.xsl"?>
<schedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://sofiadutta.github.io/fall2019/schedule.xsd" year="2019" semester="Fall">
    <course>
        <programIdentifier>CMSC</programIdentifier>
        <number>435</number>
        <title>Computer Graphics</title>
        <credit>3</credit>
        <prerequisite>CMSC313 and CMSC341 and MATH221</prerequisite>
        <description>An introduction to the fundamentals of interactive computer graphics. Topics include graphics hardware, line drawing, area filling, clipping, two-dimensional and three-dimensional geometrical transforms, three-dimensional perspective viewing, hidden surface removal, illumination, color and shading models.</description>
        <section>
            <sectionNumber>01</sectionNumber>
            <instructor>Adam Bargteil</instructor>
            <classNumber>1634</classNumber>
            <room>Interdisciplinary Life S 237</room>
            <days>MoWe</days>
            <startTime>1:00pm</startTime>
            <endTime>2:15pm</endTime>
            <status>Open</status>
        </section>
    </course>
    <course>
        <programIdentifier>CMSC</programIdentifier>
        <number>471</number>
        <title>Introduction to Artificial Intelligence</title>
        <credit>3</credit>
        <prerequisite>CMSC341 or CMSC341H</prerequisite>
        <description>This course provides a broad introduction to artificial intelligence, its sub-fields and their applications. Topics include problem-solving approaches, problem spaces and search, knowledge representation and reasoning, logic and deduction, planning, expert systems, handling uncertainty, learning and natural language understanding.</description>
        <section>
            <sectionNumber>01</sectionNumber>
            <instructor>Fereydoon Vafaei</instructor>
            <classNumber>1576</classNumber>
            <room>Interdisciplinary Life S 116A</room>
            <days>TuTh</days>
            <startTime>11:30am</startTime>
            <endTime>12:45pm</endTime>
            <status>Open</status>
        </section>
        <section>
            <sectionNumber>02</sectionNumber>
            <instructor>Fereydoon Vafaei</instructor>
            <classNumber>6428</classNumber>
            <room>Janet And Walter Sondheim 206</room>
            <days>TuTh</days>
            <startTime>4:00pm</startTime>
            <endTime>5:15pm</endTime>
            <status>Open</status>
        </section>
        <section>
            <sectionNumber>03</sectionNumber>
            <instructor>Musad Haque</instructor>
            <classNumber>8283</classNumber>
            <room>Fine Arts 303</room>
            <days>TuTh</days>
            <startTime>5:30pm</startTime>
            <endTime>6:45pm</endTime>
            <status>Open</status>
        </section>
    </course>
</schedule>
